### ISSUE TITLE
关于漫画翻译手动绘制后图片出现色调分离的问题

### ISSUE THREAD

**Issue by Galihad0625** [PantsuDango/Dango-Translator#155]
全彩漫画自动翻译后进行手动绘制，图片会出现色调分离的问题，且分离程度随使用次数增加。

![3](https://github.com/user-attachments/assets/c91676c0-28dd-44ee-8956-47032e011b51)

![00](https://github.com/user-attachments/assets/2839ff88-92ca-4ee8-b3b5-f8f1c708e43b)

*可以通过删除\dango_manga\tmp下的XXX_ipt.jpeg文件，然后重新渲染文字手动解决（强行重新消除文字）

**Comment by PantsuDango** [comment]
你好，感谢反馈。
此问题系图片的缓存使用了jpeg格式导致，我会在新的5.4开始恢复使用png格式作为缓存，此问题应该不会在出现。
5.4版本将在9.30晚上发布。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月30日(周一) 凌晨1:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 关于漫画翻译手动绘制后图片出现色调分离的问题 (Issue #155)




 
全彩漫画自动翻译后进行手动绘制，图片会出现色调分离的问题，且分离程度随使用次数增加。
 
3.jpeg (view on web)
 
00.png (view on web)
 
*可以通过删除\dango_manga\tmp下的XXX_ipt.jpeg文件，然后重新渲染文字手动解决（强行重新消除文字）

**Comment by Galihad0625** [comment]
> 你好，感谢反馈。 此问题系图片的缓存使用了jpeg格式导致，我会在新的5.4开始恢复使用png格式作为缓存，此问题应该不会在出现。 5.4版本将在9.30晚上发布。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月30日(周一) 凌晨1:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [PantsuDango/Dango-Translator] 关于漫画翻译手动绘制后图片出现色调分离的问题 (Issue #155) 全彩漫画自动翻译后进行手动绘制，图片会出现色调分离的问题，且分离程度随使用次数增加。 3.jpeg (view on web) 00.png (view on web) *可以通过删除\dango_manga\tmp下的XXX_ipt.jpeg文件，然后重新渲染文字手动解决（强行重新消除文字） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢回复

**Comment by PantsuDango** [comment]
你方便的话，可以加一下qq群744892789，我把修复的版本发你试试先，看看是不是可以解决你说的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月30日(周一) 凌晨1:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 关于漫画翻译手动绘制后图片出现色调分离的问题 (Issue #155)




  
你好，感谢反馈。 此问题系图片的缓存使用了jpeg格式导致，我会在新的5.4开始恢复使用png格式作为缓存，此问题应该不会在出现。 5.4版本将在9.30晚上发布。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年9月30日(周一) 凌晨1:06 收件人: @.&gt;; 抄送: @.*&gt;; 主题: [PantsuDango/Dango-Translator] 关于漫画翻译手动绘制后图片出现色调分离的问题 (Issue #155) 全彩漫画自动翻译后进行手动绘制，图片会出现色调分离的问题，且分离程度随使用次数增加。 3.jpeg (view on web) 00.png (view on web) 可以通过删除\dango_manga\tmp下的XXX_ipt.jpeg文件，然后重新渲染文字手动解决（强行重新消除文字） — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
感谢回复

**Comment by PantsuDango** [comment]
此问题已在最新版本修复
