### ISSUE TITLE
离线OCR识别英文识别度问题

### ISSUE THREAD

**Issue by WuYang9** [PantsuDango/Dango-Translator#43]
软件没用多久，感觉挺好的，就是离线OCR识别英文感人。百度OCR因为是最近注册所以限额太大不想用。希望之后能改进离线OCR识别能力吧。辛苦作者了。
![屏幕截图 2021-08-26 133748](https://user-images.githubusercontent.com/81015666/130907181-3fbdd0e4-53a4-4bde-869a-5eef1ed27dcd.png)
![屏幕截图 2021-08-26 133801](https://user-images.githubusercontent.com/81015666/130907185-f44642ee-b4ed-472f-a835-bd29e07993a3.png)

**Comment by SakuOtonashi** [comment]
你可以使用我写的这个 https://github.com/SakuOtonashi/gosseract ，之前就是因为玩 ChronoClock 英文识别感人就自己写了一个

**Comment by PantsuDango** [comment]
hhhh~ 前面看到一直没回复你还~ 

我也会写go，但是我之前从没想过用go来做机器学习项目
go最大的好处就是编译成执行文件特别方便，不知道这个能不能直接编译成一个很方便的exe直接打开就用
还是说需要另外在环境装tesseract和语料包呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 中午1:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 离线OCR识别英文识别度问题 (#43)





 
你可以使用我写的这个 https://github.com/SakuOtonashi/gosseract ，之前就是因为玩 ChronoClock 英文识别感人就自己写了一个
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SakuOtonashi** [comment]
> 

应该不用，你试一下 Releases 栏里的可执行文件能不能直接执行，我在 Readme 里写的是给继续开发需要注意的地方。
