### ISSUE TITLE
请问site-packages\qpt这个包是由您维护的么？

### ISSUE THREAD

**Issue by qiansen1386** [PantsuDango/Dango-Translator#49]
我本地的terminal是utf-8的codepage，我直接运行OCR会导致下面的报错
```powershell
raceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\DangoTranslate-Ver3.6.2\DangoOCR-Ver1.2\Python\lib\site-packages\qpt\run.py", line 12, in <module>
    module = RunExecutableM
# ....
  File "D:\DangoTranslate-Ver3.6.2\DangoOCR-Ver1.2\Python\lib\site-packages\qpt\kernel\tools\terminal.py", line 67, in handle
    msg = line.decode('gbk').strip("b'").strip("\n").strip(SHELL_ACT)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 47: illegal multibyte sequence
```

我手动把`site-packages\qpt\kernel\tools\terminal.py`这个文件里所有的gbk替换成utf8了就可以启动，确实国内很少有人会换code page。

我不知道这个包是由您维护的么？如果是的话，换成`sys.stdout.encoding`会不会更好一些？

**Comment by PantsuDango** [comment]
说实话，你这个邮件让我非常震惊。
这个问题已经修复了，但会在新版本才体现，你的解决思路是对的。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 晚上9:56
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 请问site-packages\qpt这个包是由您维护的么？ (Issue #49)





 
我本地的terminal是utf-8的codepage，我直接运行OCR会导致下面的报错
 raceback (most recent call last):   File "<string&gt;", line 1, in <module&gt;   File "D:\DangoTranslate-Ver3.6.2\DangoOCR-Ver1.2\Python\lib\site-packages\qpt\run.py", line 12, in <module&gt;     module = RunExecutableM # ....   File "D:\DangoTranslate-Ver3.6.2\DangoOCR-Ver1.2\Python\lib\site-packages\qpt\kernel\tools\terminal.py", line 67, in handle     msg = line.decode('gbk').strip("b'").strip("\n").strip(SHELL_ACT) UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 47: illegal multibyte sequence
 
我手动把site-packages\qpt\kernel\tools\terminal.py这个文件里所有的gbk替换成utf8了就可以启动，确实国内很少有人会换code page。
 
我不知道这个包是由您维护的么？如果是的话，换成sys.stdout.encoding会不会更好一些？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
