### ISSUE TITLE
手动翻译的快捷键会失效

### ISSUE THREAD

**Issue by qiansen1386** [PantsuDango/Dango-Translator#50]
有的时候手动翻译的快捷键会失效，怎么按都不起作用，要手动点那个小三角。
可是这个键会自动隐藏，而且也太小了。
最好翻译成功的时候能给个反馈。

可以问一下旁边的团子有什么用么？点他好像只会说话。
如果旁边的团子可以点，点了可以触发翻译就好了。

**Comment by PantsuDango** [comment]
翻译键一直都存在问题，可能会被系统自动屏蔽，该问题会在未来发布的4.0版本得到解决；
旁边团子会在新版本内被取消，它目前仅是个人兴趣，没有实际意义；
关于翻译成功的反馈，希望能得到你的建议，具体是什么个形式





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 晚上11:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 手动翻译的快捷键会失效 (Issue #50)





 
有的时候手动翻译的快捷键会失效，怎么按都不起作用，要手动点那个小三角。
 可是这个键会自动隐藏，而且也太小了。
 最好翻译成功的时候能给个反馈。
 
可以问一下旁边的团子有什么用么？点他好像只会说话。
 如果旁边的团子可以点，点了可以触发翻译就好了。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qiansen1386** [comment]
比如边框闪 200ms 柔和的白光之类的？既要有反馈还不能喧宾夺主。您新版本用啥什么框架编写啊？

**Comment by PantsuDango** [comment]
还是PyQt捏




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月9日(星期二) 晚上9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 手动翻译的快捷键会失效 (Issue #50)





 
比如边框闪 200ms 柔和的白光之类的？既要有反馈还不能喧宾夺主。您新版本用啥什么框架编写啊？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
