### ISSUE TITLE
自动模式能调节ocr频率吗

### ISSUE THREAD

**Issue by Limiyali** [PantsuDango/Dango-Translator#51]
现在是直接拉满，有点吃不消啊。

**Comment by PantsuDango** [comment]
你把自动翻译的间隔调大一点，可以缓解你的情况。或者等我发布新版本用在线OCR(快了)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 上午10:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 自动模式能调节ocr频率吗 (Issue #51)





 
现在是直接拉满，有点吃不消啊。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PantsuDango** [comment]
此issu我先关闭啦~
