### ISSUE TITLE
缺少字符\uo131

### ISSUE THREAD

**Issue by vbnshi** [PantsuDango/Dango-Translator#54]
翻译的时候发现提示错误gbk缺少\uo131

**Comment by PantsuDango** [comment]
直接私聊加我QQ我给你解决 394883561




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 下午2:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 缺少字符\uo131 (Issue #54)





 
翻译的时候发现提示错误gbk缺少\uo131
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PantsuDango** [comment]
此问题已修复~ 详见4.0.4版本

**Comment by PantsuDango** [comment]
此issu我先关闭啦~
