### ISSUE TITLE
请问适配了mac吗还是要自己编译呀？

### ISSUE THREAD

**Issue by AlanDinkle** [PantsuDango/Dango-Translator#55]
因为我不太会然后也没找到.dmg文件…
抱歉打扰啦

**Comment by PantsuDango** [comment]
目前还没有适配mac呢，不好意思




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 晚上10:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 请问适配了mac吗还是要自己编译呀？ (Issue #55)





 
因为我不太会然后也没找到.dmg文件…
 抱歉打扰啦
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlanDinkle** [comment]
好吧谢谢😶
