### ISSUE TITLE
Linux Ubuntu无法使用

### ISSUE THREAD

**Issue by liziru** [PantsuDango/Dango-Translator#8]
我按照requirements.txt安装了依赖，可是还是不能跑。执行“python main.py” 报错结果如下：
`Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from Init import MainInterface
  File "/home/lee/Dango-Translator/Init.py", line 10, in <module>
    from Translate import translate
ModuleNotFoundError: No module named 'Translate'
`
请问我该如何解决？ 多谢。

**Comment by PantsuDango** [comment]
你的报错已经提示你了 错误是由于“ No module named 'Translate' ”

**Comment by PantsuDango** [comment]
说明你的Translate.py文件 并不和Main.py在同一目录下 所以找不到该自建模块

**Comment by huimeilongyin** [comment]
退订

胖次团子 <notifications@github.com> 于 2020年6月5日周五 下午8:05写道：

**Comment by helingping** [comment]
> 我按照requirements.txt安装了依赖，可是还是不能跑。执行“python main.py” 报错结果如下：
> `Traceback (most recent call last): File "main.py", line 9, in <module> from Init import MainInterface File "/home/lee/Dango-Translator/Init.py", line 10, in <module> from Translate import translate ModuleNotFoundError: No module named 'Translate' `
> 请问我该如何解决？ 多谢。

Translate.py 是要自己添加吗，好像没有说明文档哟，我也碰到这个问题了。

**Comment by PantsuDango** [comment]
报错说的是你找不到Translate，Translate在translate.py里，你保证你有translate.py这个文件且和其他文件放在同一目录下即可，还有问题可直接加我QQ帮你看



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hlp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 晚上9:44
收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;"胖次团子"<394883561@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] Linux Ubuntu无法使用 (#8)





  
我按照requirements.txt安装了依赖，可是还是不能跑。执行“python main.py” 报错结果如下：
 Traceback (most recent call last): File "main.py", line 9, in <module&gt; from Init import MainInterface File "/home/lee/Dango-Translator/Init.py", line 10, in <module&gt; from Translate import translate ModuleNotFoundError: No module named 'Translate' 
 请问我该如何解决？ 多谢。
  
Translate.py 是要自己添加吗，好像没有说明文档哟，我也碰到这个问题了。

**Comment by helingping** [comment]
> 报错说的是你找不到Translate，Translate在translate.py里，你保证你有translate.py这个文件且和其他文件放在同一目录下即可，还有问题可直接加我QQ帮你看
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"hlp"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月8日(星期三) 晚上9:44 收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;; 抄送:&nbsp;"胖次团子"<394883561@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [PantsuDango/Dango-Translator] Linux Ubuntu无法使用 (#8) 我按照requirements.txt安装了依赖，可是还是不能跑。执行“python main.py” 报错结果如下： Traceback (most recent call last): File "main.py", line 9, in <module&gt; from Init import MainInterface File "/home/lee/Dango-Translator/Init.py", line 10, in <module&gt; from Translate import translate ModuleNotFoundError: No module named 'Translate' 请问我该如何解决？ 多谢。 Translate.py 是要自己添加吗，好像没有说明文档哟，我也碰到这个问题了。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我知道原因了，团子之前肯定是改过大小写啦。 我把目录下的translate.py --->改成 大写的 Translate.py，就可以跑起来啦。

**Comment by helingping** [comment]
![image](https://user-images.githubusercontent.com/10951158/86927415-e705dc00-c165-11ea-8edf-d46b32aadfe8.png)
一开始clone下来的时候，是小写的 translate.py

**Comment by PantsuDango** [comment]
是github改的 QAQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hlp"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 晚上9:56
收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;"胖次团子"<394883561@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] Linux Ubuntu无法使用 (#8)





  
报错说的是你找不到Translate，Translate在translate.py里，你保证你有translate.py这个文件且和其他文件放在同一目录下即可，还有问题可直接加我QQ帮你看
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"hlp"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月8日(星期三) 晚上9:44 收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;; 抄送:&nbsp;"胖次团子"<394883561@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [PantsuDango/Dango-Translator] Linux Ubuntu无法使用 (#8) 我按照requirements.txt安装了依赖，可是还是不能跑。执行“python main.py” 报错结果如下： Traceback (most recent call last): File "main.py", line 9, in <module&gt; from Init import MainInterface File "/home/lee/Dango-Translator/Init.py", line 10, in <module&gt; from Translate import translate ModuleNotFoundError: No module named 'Translate' 请问我该如何解决？ 多谢。 Translate.py 是要自己添加吗，好像没有说明文档哟，我也碰到这个问题了。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我知道原因了，团子之前肯定是改过大小写啦。 我把目录下的translate.py ---&gt;改成 大写的 Translate.py，就可以跑起来啦。
