### ISSUE TITLE
公共deepl 提示我抽风了 

### ISSUE THREAD

**Issue by hjie** [PantsuDango/Dango-Translator#93]
你们碰到了吗，是我自己的问题还是deepl没法用了？

**Comment by PantsuDango** [comment]
首先要确认你的公共翻译模块可以使用，然后的话，deepl是外国的源，不确定你的网络是否可以连上。
相关问题最好来交流群讨论，有客服会协助你，群号794893584



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月3日(周一) 晚上8:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 公共deepl 提示我抽风了  (Issue #93)




 
你们碰到了吗，是我自己的问题还是deepl没法用了？

**Comment by hjie** [comment]
反馈：
有道可以使用，deepl提示抽风
以全局ss测试过，deepl不可用

**Comment by PantsuDango** [comment]
收到，我近期会大修所有公共翻译的接口



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月5日(周三) 中午11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 公共deepl 提示我抽风了  (Issue #93)




 
反馈：
 有道可以使用，deepl提示抽风
 以全局ss测试过，deepl不可用

**Comment by PantsuDango** [comment]
代理是支持的，你直接开代理翻译的流量就会走代理了。目前谷歌翻译用不了不是因为代理访问问题，近期我在修复整个公共翻译，之后就可以用了

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月24日(周一) 晚上8:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 公共deepl 提示我抽风了  (Issue #93)




 
类似的还有谷歌翻译，建议为 administrator cmd 加入 http 代理支持，这个简单的给新建的目标 cmd 设置环境值即可，这个功能可以很有用，感谢 @PantsuDango

**Comment by NewBugger** [comment]
> 代理是支持的，你直接开代理翻译的流量就会走代理了

是我没有看到代理的设置项吗？

**Comment by PantsuDango** [comment]
你给你的代理开全局模式或者系统代理就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月25日(周二) 上午8:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 公共deepl 提示我抽风了  (Issue #93)




  
代理是支持的，你直接开代理翻译的流量就会走代理了
  
是我没有看到代理的设置项吗？

**Comment by NewBugger** [comment]
> 你给你的代理开全局模式或者系统代理就可以了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年10月25日(周二) 上午8:32 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PantsuDango/Dango-Translator] 公共deepl 提示我抽风了 (Issue #93) 代理是支持的，你直接开代理翻译的流量就会走代理了 是我没有看到代理的设置项吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

不考虑在应用内加入代理吗

**Comment by PantsuDango** [comment]
好像确实，你说的有道理，我记录一下这个需要，下次更新补上～感谢提醒



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月25日(周二) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 公共deepl 提示我抽风了  (Issue #93)




  
你给你的代理开全局模式或者系统代理就可以了
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年10月25日(周二) 上午8:32 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [PantsuDango/Dango-Translator] 公共deepl 提示我抽风了 (Issue #93) 代理是支持的，你直接开代理翻译的流量就会走代理了 是我没有看到代理的设置项吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
不考虑在应用内加入代理吗
